# Generated by Django 3.0.6 on 2020-08-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='title',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
